# full spec: https://github.com/thedodd/trunk/blob/master/Trunk.toml

[build]
target = "frontend/index.html"
filehash = false

[clean]
dist = "frontend/dist"

[[proxy]]
backend = "http://127.0.0.1:3000/api/"
